[workspace]
members = ["plugins/*"]
resolver = "2"

[workspace.dependencies]
# plugins
actions = { path = "plugins/actions" }
cauldron = { path = "plugins/cauldron" }
cauldron_ui = { path = "plugins/cauldron_ui" }
encounter = { path = "plugins/encounter" }
encounter_ui = { path = "plugins/encounter_ui" }
game_instance = { path = "plugins/game_instance" }
monsters = { path = "plugins/monsters" }
turns = { path = "plugins/turns" }

# bevy
bevy = { version = "0.13", default-features = false }
bevy_rand = { version = "0.6", features = ["wyrand"] }
bevy_prng = { version = "0.6", features = ["wyrand"] }
bevy_anytoasts = { git = "https://github.com/GroveStStudios/bevy_anytoasts" }

# stdx
anyhow = "1.0"
rand_core = { version = "0.6" }
thiserror = "1.0"

[package]
name = "tennis"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
actions = { workspace = true }
cauldron = { workspace = true }
cauldron_ui = { workspace = true }
encounter = { workspace = true }
encounter_ui = { workspace = true }
game_instance = { workspace = true }
turns = { workspace = true }
