[workspace]
members = ["plugins/*"]
resolver = "2"

[workspace.dependencies]
# plugins

# bevy
bevy = { version = "0.14", default-features = false }
bevy_rand = { version = "0.6", features = ["wyrand"] }
bevy_prng = { version = "0.6", features = ["wyrand"] }
bevy_anyhow_alert = "0.3"

# stdx
anyhow = "1.0"
rand_core = { version = "0.6" }
thiserror = "1.0"

[package]
name = "pewpewboom"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
